### ISSUE TITLE
Open Graph parametrit ja kuva kuntoon

### ISSUE THREAD

**Issue by pe3** [okffi/open-api-definition#26]
Tämä ratkaisee miltä sivusto näyttää FB-feedissä. 

Tuolta [FB:n debuggerista](https://developers.facebook.com/tools/debug/og/object/) näkee, että kaikki ei oo kunnossa. 

Logo-kuva on kovin matalaresoluutioinen.

Vaikka sivuston korjais, FB ei välttämättä (ainakaan kovinkaan pian), havaitse muutosta. Se kannattaa trigata tuolta: "Fetch new scrape information".

**Comment by Mygee** [comment]
@d2s lupasi hoitaa nämä kuntoon ja juttelimme tästä lounaan parissa tänään.

**Comment by d2s** [comment]
Tuossa pari Pull Requestia joissa korjattu ainakin osa ongelmista.

Vielä pitää mergen jälkeen tehdä todennäköisesti jotain pieniä korjauksia.
(Kunhan pääsee testaamaan Facebookin työkalulla, kun Open Graph tagit ovat taas paikoillaan.)

**Comment by d2s** [comment]
Tässä testasin [Facebookin työkalulla](https://developers.facebook.com/tools/debug/og/object/) mitkä asiat ovat vielä korjattavana:

- "Object at URL 'http://avoinrajapinta.fi/' of type 'website' is invalid because the given value 'fi' for property 'og:locale:locale' could not be parsed as type 'enum'."
- "Object Invalid Value: Object at URL 'http://avoinrajapinta.fi/' of type 'website' is invalid because the given value 'fi' for property 'og:locale:locale' could not be parsed as type 'enum'."

![screenshot from 2015-12-23 01 28 12 avoinrajapinta open graph object debugger](https://cloud.githubusercontent.com/assets/135053/11968395/90e563d6-a914-11e5-96d0-57e9922b8a46.png)

Asiaan liittyvä dokumentaatio [The Open Graph protocol](http://ogp.me/) -sivulla tosin kertoo että `og:locale` on ei-pakollinen meta-tieto (_Optional Metadata_), jota [Facebook käyttää](https://developers.facebook.com/docs/opengraph/guides/internationalization) eri kieliversioiden selostus-tekstien hakemiseen.

Ongelma voidaan korjata helpoiten poistamalla (tai kommentoimalla pois) ylimääräinen rivi 30 [`_includes/head.html`](https://github.com/okffi/open-api-definition/blob/gh-pages/_includes/head.html#L30) -tiedostosta.
```html
<meta property="og:locale" content="{{ site.lang }}">
```

**Comment by d2s** [comment]
Ongelmat korjattu.
